# Generated by Django 6.0.4 on 2026-05-02 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jayapp', '0002_product_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
